apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: langchain-chatbot-pipeline
  annotations:
    scenarios.ai.sap.com/description: "PR Registration with AI Document Extraction and Vendor Evaluation"
    scenarios.ai.sap.com/name: "PR Automation"
    executables.ai.sap.com/description: "Extracts PR data, evaluates vendors, and registers the PR"
    executables.ai.sap.com/name: "PR Registration"
  labels:
    scenarios.ai.sap.com/id: "purchase-request"
    ai.sap.com/version: "7.0"
spec:
  imagePullSecrets:
    - name: dockercred
  entrypoint: pr-workflow
  templates:
  - name: pr-workflow
    steps:
    - - name: pr-workmodel
        template: mycodeblock1
  - name: mycodeblock1
    container:
      image: docker.io/227102/agnbtphk25img:01
      command: ["/bin/sh", "-c"]
      args: 
      - "python /app/src/main.py"
